name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Create Gradle Wrapper Files
      run: |
        mkdir -p gradle/wrapper
        echo 'distributionBase=GRADLE_USER_HOME' > gradle/wrapper/gradle-wrapper.properties
        echo 'distributionPath=wrapper/dists' >> gradle/wrapper/gradle-wrapper.properties
        echo 'distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip' >> gradle/wrapper/gradle-wrapper.properties
        echo 'zipStoreBase=GRADLE_USER_HOME' >> gradle/wrapper/gradle-wrapper.properties
        echo 'zipStorePath=wrapper/dists' >> gradle/wrapper/gradle-wrapper.properties
        
        # Download gradle-wrapper.jar
        curl -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.0.0/gradle/wrapper/gradle-wrapper.jar
        
        # Create gradlew script if it doesn't exist
        if [ ! -f gradlew ]; then
          curl -o gradlew https://raw.githubusercontent.com/gradle/gradle/v8.0.0/gradle/wrapper/gradlew
          chmod +x gradlew
        fi
        
        # Create gradlew.bat script if it doesn't exist
        if [ ! -f gradlew.bat ]; then
          curl -o gradlew.bat https://raw.githubusercontent.com/gradle/gradle/v8.0.0/gradle/wrapper/gradlew.bat
        fi
      

      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk